config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :movies do

member do
  post :join
  post :quit
end

    resources :critics
  end

namespace :account do
  resources :movies
  resources :critics
end

root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/critic.rb
class Critic < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  validates :content, presence: true

  scope :recent, -> { order("created_at DESC")}
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :critics
  validates :title, presence: true
  has_many :movie_relationships
  has_many :members, through: :movie_relationships, source: :user
end

app/models/movie_relationship.rb
class MovieRelationship < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :movies
         has_many :critics
         has_many :movie_relationships
         has_many :participated_movies, :through => :movie_relationships, :source => :movie

def is_member_of?(movie)
  participated_movies.include?(movie)
end

def join!(movie)
  participated_movies << movie
end

def quit!(movie)
  participated_movies.delete(movie)
end

end

app/controllers/account/critics_controller.rb
class Account::CriticsController < ApplicationController
  before_action :authenticate_user!
  def index
    @critics = current_user.critics
  end
end

app/controllers/account/movies_controller.rb
class Account::MoviesController < ApplicationController
  before_action :authenticate_user!

  def index
    @movies = current_user.participated_movies
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/critics_controller.rb
class CriticsController < ApplicationController

    before_action :authenticate_user!, :only => [:new, :create]

    def new
      @movie = Movie.find(params[:movie_id])
      @critic = Critic.new
    end

    def create
      @movie = Movie.find(params[:movie_id])
      @critic = Critic.new(critic_params)
      @critic.movie = @movie
      @critic.user = current_user

      if @critic.save
        redirect_to movie_path(@movie)
      else
        render :new
      end
    end


    private

    def critic_params
      params.require(:critic).permit(:content)
    end

  end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user! , only: [:new, :create, :edit, :update, :destroy, :join, :quit]
  before_action :find_movie_and_check_permission, only: [:edit, :update, :destroy]
  def index
    @movies = Movie.all
  end

def show
  @movie = Movie.find(params[:id])
  @critics = @movie.critics.recent.paginate(:page => params[:page], :per_page => 5)
end

def edit
end

  def new
    @movie = Movie.new
  end

def create
  @movie = Movie.new(movie_params)
  @movie.user = current_user

  if @movie.save
    current_user.join!(@movie)
redirect_to movies_path
else
  render :new
end
end

def update
if @movie.update(movie_params)
  redirect_to movie_path, notice: "Update Success!"
else
  render :edit
end
end

def destroy
  @movie.destroy
  flash[:alert] = "Movie deleted"
  redirect_to movies_path
end


def join
   @movie = Movie.find(params[:id])

    if !current_user.is_member_of?(@movie)
      current_user.join!(@movie)
      flash[:notice] = "收藏本电影成功！"
    else
      flash[:warning] = "你已收藏过本电影！"
    end

    redirect_to movie_path(@movie)
  end

def quit
    @movie = Movie.find(params[:id])

    if current_user.is_member_of?(@movie)
      current_user.quit!(@movie)
      flash[:alert] = "已取消收藏本电影！"
    else
      flash[:warning] = "你尚未收藏本电影，怎么取消 XD"
    end

    redirect_to movie_path(@movie)
  end

private
def find_movie_and_check_permission
@movie = Movie.find(params[:id])

if current_user != @movie.user
  redirect_to root_path, alert: "You have no permission."
end
end

def movie_params
  params.require(:movie).permit(:title, :description)
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = "早安！"
  end
end

app/helpers/account/critics_helper.rb
module Account::CriticsHelper
end

app/helpers/account/movies_helper.rb
module Account::MoviesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/critics_helper.rb
module CriticsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def render_movie_description(movie)
    simple_format(movie.description)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
<% user_facing_flashes.each do |key, value| %>
<div class="alert alert-dismissable alert-<%= flash_class(key) %>">
  <button class="close" data-dismiss="alert">x</button>
  <%= value %>
</div>
<% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="Container" style="margin-top: 100px;">
  <p class="text-center">Copyright ©️2017 柚子影视
    <br>Designed by
    <a href="http://courses.growthschool.com/courses/rails-101/" target=_new>Floria</a>
  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navgation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">柚子影视</a>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
        <li><%= link_to("注册", new_user_registration_path) %></li>
        <li><%= link_to("登录", new_user_session_path) %></li>
        <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Hi!, <%= current_user.email %>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li> <%= link_to("我收藏的电影", account_movies_path) %></li>
            <li> <%= link_to("我发表的影评", account_critics_path) %></li>
            <li class="divider"> </li>
            <li><%= link_to("退出", destroy_user_session_path, method: :delete) %> </li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/critics/new.html.erb
<h2 class="text-center">新增影评</h2>

<div class="col-md-4 col-md-offset-4">
  <%= simple_form_for [@movie,@critic] do |f| %>
    <div class="form-movie">
      <%= f.input :content, input_html: { class: "form-control"} %>
    </div>
    <div class="form-actions">
      <%= f.submit "Submit", disable_with: "Submiting...", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movie001</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <%= yield %>
    </div>

    <%= render "common/footer" %>

  </body>
</html>

app/views/movies/_form.html.erb
<%= simple_form_for @movie do |f| %>
  <div class="form-movie">
    <%= f.input :title, input_html: { class: "form-control"} %>
    <%= f.input :description, input_html: { class: "form-control"} %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
<% end %>

app/views/movies/_movie_item.html.erb
<tr>
  <td>#</td>
  <td><%= link_to(movie.title, movie_path(movie)) %></td>
  <td><%= render_movie_description(movie) %></td>
  <td><%= movie.user.email %></td>
  <td>
    <% if current_user && current_user == movie.user %>
    <%= link_to("Edit", edit_movie_path(movie), class: "btn btn-sm btn-default")%>
    <%= link_to("Delete", movie_path(movie), class:"btn btn-sm btn-default",
  method: :delete, data: {confirm: "Are you sure"})%>
  <% end %>
</td>

</tr>

app/views/movies/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>编辑电影</h2>

  <hr>

  <%= render "form" %>

</div>

app/views/movies/index.html.erb
<div class="col-md-12">
  <div class="movie">
    <%= link_to("New movie", new_movie_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>电影</td>
        <td>简介</td>
        <td>创建者</td>
      </tr>
    </thead>
  </tbody>
<% render :partial => "group_item", :collection => @movies, :as => :group %>
</tbody>
</table>
</div>

app/views/movies/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>新增电影</h2>

  <hr>

<%= render "form" %>

</div>

app/views/movies/show.html.erb
<div class="col-md-12">
  <div class="movie">

    <span class="pull-right">
      <% if current_user && current_user.is_member_of?(@movie) %>
        <label class="label label-success"> 已收藏 </label>
        <%= link_to("取消收藏", quit_movie_path(@movie), method: :critic, class: "btn btn-default") %>
      <% else %>
        <label class="label label-warning"> 未收藏 </label>
        <%= link_to("收藏", join_movie_path(@movie), method: :critic, class: "btn btn-default") %>
      <% end %>
    </span>

    <%= link_to("写一篇影评", new_movie_critic_path(@movie), class: "btn btn-default pull-right")%>
    <% if current_user && current_user == @movie.user %>
    <%= link_to("Edit", edit_movie_path(@movie), class: "btn btn-primary pull-right")%>
<% end %>
  </div>
  <h2><%= @movie.title %></h2>
  <p><%= @movie.description %></p>

<table class="table">
  <thead>
    <tr>
      <th>影评内容</th>
      <th>发表者</th>
      <th>发表时间</th>
    </tr>
  </thead>
  <tbody>
    <% @critics.each do |critic| %>
    <tr>
      <td><%= critic.content %></td>
      <td><%= critic.user.email %></td>
      <td><%= critic.created_at %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="text-center">
  <%= will_paginate @critics %>
</div>

</div>

app/views/welcome/index.html.erb
<h1> 欢迎来到柚子影视! </h1>